### ISSUE TITLE
n brokes npm

### ISSUE THREAD

**Issue by voronianski** [tj/n#118]
after I switch from one version to another my npm is broken...

```
MacBook-Pro-Dmitri:~ dmitri$ npm --version

module.js:340
    throw err;
          ^
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at /usr/local/bin/npm:19:11
    at Object.<anonymous> (/usr/local/bin/npm:87:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

then i do like adviced here - https://github.com/visionmedia/n/issues/101

```
curl https://npmjs.org/install.sh | sh
```

npm start working.. but then i do another switch for node version

```
n 0.8.22
```

and npm now is broken again..

it's very annoying..

**Comment by a-x-** [comment]
Happened to me as well after using latest `n` to install the latest node on node of v0.10.29 (on Raspbian)

**Comment by jucajuca** [comment]
Why is the issue closed? This is still happening.
It is very annoying to re-install node.
