### ISSUE TITLE
How to completely uninstall n?

### ISSUE THREAD

**Issue by bigblind** [tj/n#238]
I was having issues with jest not working with iojs, so I installed n to get node 0.10.x, but still got errors, so now I'm just running jest in a vm. After installing n and switching back to iojs by doing `n io stable`, npm itself just REFUSES to do anything for me, giving me the following message

```
module.js:322
    throw err;
          ^
Error: Cannot find module './clear-credentials-by-uri.js'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:230:40)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
````

What would be the best way to get my machine back into a state where at least npm works properly? Seems like uninstalling n, going back to my previously installed version of iojs would do it, but I'm open to other options.

**Comment by AdoHe** [comment]
@bigblind are you sure your module path is correct?

**Comment by bigblind** [comment]
Yes.
