### ISSUE TITLE
npm error when i change node version

### ISSUE THREAD

**Issue by younth** [tj/n#329]
i had install node and npm before on my osx  

after install n , i change node to node/5.0.0 ,then the npm is wrong, 

```
➜  ~  npm -v
module.js:339
    throw err;
    ^

Error: Cannot find module '../utils/correct-mkdir.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cache/get-stat.js:2:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

what can do for it

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
