### ISSUE TITLE
install on windows 11 failed

### ISSUE THREAD

**Issue by PTAHume** [tj/n#767]
windows 11 pro
node version: v18.16.0
npm version: 9.6.5

I ran the install command ```npm install -g n``` and got the following

```
 npm install -g n
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.1.0: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32

npm ERR! A complete log of this run can be found in: C:\Users\ASUS\AppData\Local\npm-cache\_logs\2023-05-15T16_03_27_552Z-debug-0.log
````

the log file has the following

```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.6.5
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\ASUS\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\ASUS\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 9ms
16 timing npm:load:configload Completed in 9ms
17 timing npm:load:mkdirpcache Completed in 1ms
18 timing npm:load:mkdirplogs Completed in 0ms
19 verbose title npm install n
20 verbose argv "install" "--global" "n"
21 timing npm:load:setTitle Completed in 1ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:display Completed in 3ms
24 verbose logfile logs-max:10 dir:C:\Users\ASUS\AppData\Local\npm-cache\_logs\2023-05-15T16_03_27_552Z-
25 verbose logfile C:\Users\ASUS\AppData\Local\npm-cache\_logs\2023-05-15T16_03_27_552Z-debug-0.log
26 timing npm:load:logFile Completed in 7ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 23ms
30 timing config:load:flatten Completed in 1ms
31 timing arborist:ctor Completed in 1ms
32 timing idealTree:init Completed in 5ms
33 timing idealTree:userRequests Completed in 3ms
34 silly idealTree buildDeps
35 silly fetch manifest n@*
36 silly logfile start cleaning logs, removing 2 files
37 silly logfile done cleaning log files
38 http fetch GET 200 https://registry.npmjs.org/n 1669ms (cache miss)
39 silly placeDep ROOT n@9.1.0 OK for:  want: *
40 timing idealTree:#root Completed in 1676ms
41 timing idealTree:node_modules/n Completed in 0ms
42 timing idealTree:buildDeps Completed in 1678ms
43 timing idealTree:fixDepFlags Completed in 0ms
44 timing idealTree Completed in 1688ms
45 timing command:install Completed in 1697ms
46 verbose stack Error: Unsupported platform
46 verbose stack     at checkPlatform (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\lib\index.js:53:25)
46 verbose stack     at [checkEngineAndPlatform] (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:235:9)
46 verbose stack     at Arborist.buildIdealTree (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:210:42)
46 verbose stack     at async Arborist.reify (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
46 verbose stack     at async Install.exec (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:147:5)
46 verbose stack     at async module.exports (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\lib\cli.js:89:5)
47 verbose pkgid n@9.1.0
48 verbose cwd C:\Users\ASUS
49 verbose Windows_NT 10.0.22621
50 verbose node v18.16.0
51 verbose npm  v9.6.5
52 error code EBADPLATFORM
53 error notsup Unsupported platform for n@9.1.0: wanted {"os":"!win32"} (current: {"os":"win32"})
54 error notsup Valid os:  !win32
54 error notsup Actual os: win32
55 verbose exit 1
56 timing npm Completed in 2037ms
57 verbose unfinished npm timer reify 1684166607892
58 verbose unfinished npm timer reify:loadTrees 1684166607897
59 verbose code 1
60 error A complete log of this run can be found in: C:\Users\ASUS\AppData\Local\npm-cache\_logs\2023-05-15T16_03_27_552Z-debug-0.log
```

any surgestions ?

**Comment by alexander01202** [comment]
Hey man
How were you able to solve this?

**Comment by shadowspawn** [comment]
`n` does not run in a native Windows shell, but can be used in a WSL Linux shell.

**Comment by btxtiger** [comment]
@shadowspawn This is the error from the WSL Ubuntu bash 22.04 LTS on latest Windows 11 Pro (23H2):
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.2.0: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32
```
